apiVersion: apps/v1
kind: Deployment
metadata:
  name: prbased-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prbased
  template:
    metadata:
      labels:
        app: prbased
    spec:
      containers:
      - name: express
        image: jiwoo22/prbased_test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: prbased-test
---
apiVersion: v1
kind: Service
metadata:
  name: prbased-t
spec:
  selector:
    app: prbased
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
