apiVersion: apps/v1
kind: Deployment
metadata:
  name: prbased-test
  labels:
    app: prbased-test
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prbased-test
  template:
    metadata:
      labels:
        app: prbased-test
        tier: prbased-test
    spec:
      containers:
      - name: dino
        image: jiwoo22/prbased_test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: prbased-test
---
apiVersion: v1
kind: Service
metadata:
  name: prbased-test
  labels:
    app: prbased-test
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: prbased-test
    tier: prbased-test
  type: LoadBalancer
