apiVersion: apps/v1
kind: Deployment
metadata:
  name: prbased
  labels:
    app: prbased
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prbase
  template:
    metadata:
      labels:
        app: prbased
    spec:
      containers:
      - name: hello
        image: jiwoo/prbased_test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: hello
---
apiVersion: v1
kind: Service
metadata:
  name: prbased
  labels:
    app: prbased
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: prbased
  type: LoadBalancer
