apiVersion: apps/v1
kind: Deployment
metadata:
  name: prbased
  labels:
    app: prbased
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prbased
  template:
    metadata:
      labels:
        app: prbased
        tier: prbased
    spec:
      containers:
      - name: prbased
        image: jiwoo22/prbased_test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: prbased
---
apiVersion: v1
kind: Service
metadata:
  name: prbased
  labels:
    app: prbased
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: prbased
    tier: prbased
  type: LoadBalancer
